# Generated by Django 4.2.1 on 2023-05-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_active',
        ),
    ]
