# Generated by Django 4.2.1 on 2023-06-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_artist_label_remove_album_is_active_album_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
